"""baseline schema v0.6

Revision ID: e829876f638c
Revises:
Create Date: 2026-06-10 13:20:43.716893

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e829876f638c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "countries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("iso_code", sa.String(length=5), nullable=False),
        sa.Column("country_name", sa.String(length=100), nullable=True),
        sa.Column("is_sensitive", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("iso_code"),
    )
    op.create_table(
        "data_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_name", sa.String(length=100), nullable=False),
        sa.Column("base_url", sa.String(length=300), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "info_updates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("last_update_rss", sa.DateTime(), nullable=True),
        sa.Column("last_update_json", sa.DateTime(), nullable=True),
        sa.Column("last_update_csv", sa.DateTime(), nullable=True),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "manual_overrides",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("original_name", sa.String(length=300), nullable=True),
        sa.Column("original_domain", sa.String(length=300), nullable=True),
        sa.Column("matched_name", sa.String(length=300), nullable=True),
        sa.Column("matched_domain", sa.String(length=300), nullable=True),
        sa.Column("similarity_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("similarity_level", sa.String(length=50), nullable=True),
        sa.Column("approved", sa.Boolean(), nullable=True),
        sa.Column("analyst_id", sa.Integer(), nullable=True),
        sa.Column("override_date", sa.DateTime(), nullable=True),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notification_subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(length=50), nullable=False),
        sa.Column("config_key", sa.String(length=200), nullable=False),
        sa.Column("config_value", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel", "config_key", name="uq_notif_sub"),
    )
    op.create_table(
        "source_health",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_name", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("last_check", sa.DateTime(), nullable=True),
        sa.Column("last_ok", sa.DateTime(), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("format_valid", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_name", name="uq_source_health"),
    )
    op.create_table(
        "watchlist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("domain", sa.String(length=300), nullable=True),
        sa.Column("keywords", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "certs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.String(length=100), nullable=True),
        sa.Column("team_name", sa.String(length=200), nullable=True),
        sa.Column("team_full", sa.String(length=300), nullable=True),
        sa.Column("email", sa.String(length=200), nullable=True),
        sa.Column("website", sa.String(length=300), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("country_id", sa.Integer(), nullable=True),
        sa.Column("data_source_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["countries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id"),
    )
    op.create_table(
        "cyberattacks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("victim_name", sa.String(length=300), nullable=True),
        sa.Column("domain", sa.String(length=300), nullable=True),
        sa.Column("country", sa.String(length=50), nullable=True),
        sa.Column("attack_date", sa.DateTime(), nullable=True),
        sa.Column("added", sa.DateTime(), nullable=True),
        sa.Column("discovered", sa.DateTime(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("article_url", sa.String(length=500), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "group_source_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_name", sa.String(length=100), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("raw_data", sa.Text(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_name", "source_id", name="uq_group_source"),
    )
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("parser", sa.Boolean(), nullable=True),
        sa.Column("meta", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=300), nullable=True),
        sa.Column("aliases", sa.Text(), nullable=True),
        sa.Column("country_of_origin", sa.String(length=5), nullable=True),
        sa.Column("group_type", sa.String(length=100), nullable=True),
        sa.Column("extensions", sa.Text(), nullable=True),
        sa.Column("lineage", sa.Text(), nullable=True),
        sa.Column("btc_addresses", sa.Text(), nullable=True),
        sa.Column("profile_urls", sa.Text(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_name"),
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("legal_name", sa.String(length=300), nullable=True),
        sa.Column("display_name", sa.String(length=300), nullable=True),
        sa.Column("domain", sa.String(length=300), nullable=True),
        sa.Column("lei", sa.String(length=20), nullable=True),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("country_id", sa.Integer(), nullable=True),
        sa.Column("employee_count", sa.Integer(), nullable=True),
        sa.Column("gleif_id", sa.String(length=50), nullable=True),
        sa.Column("wikidata_id", sa.String(length=20), nullable=True),
        sa.Column("opencorporates_id", sa.String(length=100), nullable=True),
        sa.Column("enrichment_source", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["countries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("domain"),
        sa.UniqueConstraint("lei"),
    )
    op.create_table(
        "certs_constituency",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cert_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(
            ["cert_id"],
            ["certs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "group_btc_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(length=100), nullable=False),
        sa.Column("tx_hash", sa.String(length=100), nullable=False),
        sa.Column("amount_btc", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("amount_usd", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("tx_date", sa.DateTime(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address", "tx_hash", name="uq_btc_tx"),
    )
    op.create_table(
        "group_comms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("channel_type", sa.String(length=50), nullable=False),
        sa.Column("channel_value", sa.String(length=500), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "channel_type", "channel_value", name="uq_group_comm"),
    )
    op.create_table(
        "group_locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("fqdn", sa.String(length=300), nullable=True),
        sa.Column("slug", sa.String(length=300), nullable=True),
        sa.Column("title", sa.String(length=100), nullable=True),
        sa.Column("type", sa.String(length=50), nullable=True),
        sa.Column("available", sa.Boolean(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("lastscrape", sa.DateTime(), nullable=True),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "group_references",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "url", name="uq_group_ref"),
    )
    op.create_table(
        "group_tools",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("tool_name", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "category", "tool_name", name="uq_group_tool"),
    )
    op.create_table(
        "group_ttps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("tactic_id", sa.String(length=20), nullable=False),
        sa.Column("tactic_name", sa.String(length=100), nullable=False),
        sa.Column("technique_id", sa.String(length=20), nullable=False),
        sa.Column("technique_name", sa.String(length=200), nullable=False),
        sa.Column("technique_details", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "technique_id", name="uq_group_ttp"),
    )
    op.create_table(
        "organization_identifiers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("identifier_type", sa.String(length=50), nullable=True),
        sa.Column("identifier_value", sa.String(length=100), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "victims",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("victim_name", sa.String(length=300), nullable=True),
        sa.Column("domain", sa.String(length=300), nullable=True),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("country_id", sa.Integer(), nullable=True),
        sa.Column("attackdate", sa.DateTime(), nullable=True),
        sa.Column("discovered", sa.DateTime(), nullable=True),
        sa.Column("claim_url", sa.String(length=300), nullable=True),
        sa.Column("screenshot", sa.String(length=300), nullable=True),
        sa.Column("url", sa.String(length=300), nullable=True),
        sa.Column("activity", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["countries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("domain", "attackdate", name="uq_victim_domain_date"),
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("watchlist_id", sa.Integer(), nullable=False),
        sa.Column("victim_id", sa.Integer(), nullable=False),
        sa.Column("match_field", sa.String(length=50), nullable=False),
        sa.Column("seen", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["victim_id"],
            ["victims.id"],
        ),
        sa.ForeignKeyConstraint(
            ["watchlist_id"],
            ["watchlist.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "enrichment_review",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("victim_id", sa.Integer(), nullable=False),
        sa.Column("candidate_org_id", sa.Integer(), nullable=False),
        sa.Column("match_method", sa.String(length=50), nullable=True),
        sa.Column("match_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("enrichment_source", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["victim_id"],
            ["victims.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "victim_duplicates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("victim_id", sa.Integer(), nullable=False),
        sa.Column("dup_attackdate", sa.DateTime(), nullable=True),
        sa.Column("dup_date", sa.DateTime(), nullable=True),
        sa.Column("dup_group", sa.String(length=100), nullable=True),
        sa.Column("dup_link", sa.String(length=300), nullable=True),
        sa.ForeignKeyConstraint(
            ["victim_id"],
            ["victims.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "victim_infostealer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("victim_id", sa.Integer(), nullable=False),
        sa.Column("employees", sa.Integer(), nullable=True),
        sa.Column("employees_url", sa.Integer(), nullable=True),
        sa.Column("thirdparties", sa.Integer(), nullable=True),
        sa.Column("thirdparties_domain", sa.Integer(), nullable=True),
        sa.Column("users", sa.Integer(), nullable=True),
        sa.Column("users_url", sa.Integer(), nullable=True),
        sa.Column("last_update", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["victim_id"],
            ["victims.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "victim_organizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("victim_id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("match_method", sa.String(length=50), nullable=True),
        sa.Column("match_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("matched_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["victim_id"],
            ["victims.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("victim_id", "organization_id", name="uq_victim_org"),
    )
    op.create_table(
        "victim_press",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("victim_id", sa.Integer(), nullable=False),
        sa.Column("press_link", sa.String(length=300), nullable=True),
        sa.Column("press_source", sa.Text(), nullable=True),
        sa.Column("press_summary", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["victim_id"],
            ["victims.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "victim_updates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("victim_id", sa.Integer(), nullable=False),
        sa.Column("update_date", sa.DateTime(), nullable=True),
        sa.Column("update_description", sa.Text(), nullable=True),
        sa.Column("update_link", sa.String(length=300), nullable=True),
        sa.ForeignKeyConstraint(
            ["victim_id"],
            ["victims.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("victim_updates")
    op.drop_table("victim_press")
    op.drop_table("victim_organizations")
    op.drop_table("victim_infostealer")
    op.drop_table("victim_duplicates")
    op.drop_table("enrichment_review")
    op.drop_table("alerts")
    op.drop_table("victims")
    op.drop_table("organization_identifiers")
    op.drop_table("group_ttps")
    op.drop_table("group_tools")
    op.drop_table("group_references")
    op.drop_table("group_locations")
    op.drop_table("group_comms")
    op.drop_table("group_btc_transactions")
    op.drop_table("certs_constituency")
    op.drop_table("organizations")
    op.drop_table("groups")
    op.drop_table("group_source_data")
    op.drop_table("cyberattacks")
    op.drop_table("certs")
    op.drop_table("watchlist")
    op.drop_table("source_health")
    op.drop_table("notification_subscriptions")
    op.drop_table("manual_overrides")
    op.drop_table("info_updates")
    op.drop_table("data_sources")
    op.drop_table("countries")
    # ### end Alembic commands ###
